apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: school-management-app
  description: A Django-based school management system with student and teacher dashboards.
  annotations:
    backstage.io/source-location: url:https://github.com/rahulgrt2702/backstage-poc/tree/main
    github.com/project-slug: rahulgrt2702/backstage-poc
    backstage.io/techdocs-ref: dir:docs
    backstage.io/kubernetes-id: demo-portal
    backstage.io/ci-build: github-actions
spec:
  type: service
  lifecycle: production
  owner: team-education
  system: school-platform
